rag_research_task:
  description: >
    Answer the user question based solely on the provided context.
  expected_output: >
    A fully detailed answer to the user question, divided in paragraphs.
  agent: rag_researcher

