research_task:
  description: >
    Conduct a thorough research about finance to answer the user query.
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A fully detailed answer to the user query.
    Each argument is expanded as a full section of information.
  agent: researcher
