reformulation_task:
  description: >
    Analyze and decompose the query into sub-queries 
    corresponding to each company.
  expected_output: >
    A minimal, comprehensive list of sub-queries, 
    each focusing on only one company.
  agent: reformulator