reformulation_task:
  description: >
    Reason and decompose the query into sub-queries corresponding to subsequent steps.
  expected_output:  >
    A minimal list of subsequent sub-queries for each invividual company and year.
  agent: reformulator