extraction_task:
  description: >
   Extract the most important information from the user query.
  expected_output:  >
   The most important information about the user query: {query}.
  agent: extractor