sec_research_task:
  description: >
    Retrieve the SEC Edgar financial filings that are relevant to the user query.
  expected_output: >
    The full path of the saved SEC Edgar text file.
  agent: sec_researcher

