version: '1'
services:
  document_comparison_service:
    build: 
      context: ../
      dockerfile: document_comparison/docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/document_comparison/data